spring:
  application:
    name: project-service
  boot:
    admin:
      client:
        enabled: true

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
